In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/Colab Notebooks/std2024/Session07 - 유형별로 실습하는 머신러닝

/content/drive/MyDrive/Colab Notebooks/std2024/Session07 - 유형별로 실습하는 머신러닝


In [ ]:
import pandas as pd

In [ ]:
featuresData = pd.read_csv("../dataset/feature_regression_example.csv")

In [ ]:
A. 데이터 전처리

SyntaxError: invalid syntax (<ipython-input-12-ac39bfc73662>, line 1)

In [ ]:
### A-1. 타입 통합 / 특성 숫자컬럼 추가

In [ ]:
featuresData

REGIONID PRODUCTGROUP      PRODUCT      ITEM  YEARWEEK  YEAR  WEEK  \
0    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201501  2015     1   
1    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201502  2015     2   
2    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201503  2015     3   
3    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201504  2015     4   
4    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201505  2015     5   
..              ...          ...          ...       ...       ...   ...   ...   
100  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201648  2016    48   
101  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201649  2016    49   
102  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201650  2016    50   
103  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201651  2016    51   
104  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201652  2016    52   

      QTY HOLIDAY  HCLUS PROMOTION  PRO_PERCENT  
0    1225       Y      1         Y     0.209442  
1     968       N      4         Y     0.209442  
2    1209       N      4         Y     0.208155  
3    1810       Y      2         Y     0.208155  
4    1773       N      4         Y     0.208155  
..    ...     ...    ...       ...          ...  
100  2412       Y      0         Y     0.421888  
101  1955       N      4         Y     0.421888  
102  1800       N      4         Y     0.352361  
103  1173       N      4         Y     0.352361  
104   332       Y      1         Y     0.352361  

[105 rows x 12 columns]

In [ ]:
featuresData.HOLIDAY

0      Y
1      N
2      N
3      Y
4      N
      ..
100    Y
101    N
102    N
103    N
104    Y
Name: HOLIDAY, Length: 105, dtype: object

In [ ]:
featuresData.HOLIDAY.drop_duplicates()

0    Y
1    N
Name: HOLIDAY, dtype: object

In [14]:
featuresData["REGIONID"] = featuresData["REGIONID"].astype(str)

In [15]:
featuresData["PRODUCTGROUP"] = featuresData["PRODUCTGROUP"].astype(str)

In [16]:
featuresData["PRODUCT"] = featuresData["PRODUCT"].astype(str)

In [17]:
featuresData["ITEM"] = featuresData["ITEM"].astype(str)

In [18]:
featuresData["YEARWEEK"] = featuresData["YEARWEEK"].astype(int)

In [19]:
featuresData["YEAR"] = featuresData["YEAR"].astype(int)

In [20]:
featuresData["WEEK"] = featuresData["WEEK"].astype(int)

In [21]:
featuresData["QTY"] = featuresData["QTY"].astype(float)

In [22]:
featuresData["HOLIDAY"] = featuresData["HOLIDAY"].astype(str)

In [23]:
featuresData["HCLUS"] = featuresData["HCLUS"].astype(int)

In [25]:
featuresData["PROMOTION"] = featuresData["PROMOTION"].astype(str)

In [26]:
featuresData["PRO_PERCENT"] = featuresData["PRO_PERCENT"].astype(float)

In [27]:
import numpy as np

In [28]:
np.where( featuresData.REGIONID =="Y", 1, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.where( featuresData.HOLIDAY == "Y", 1,0)

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1])

In [34]:
featuresData["LE_HOLI"] = np.where( featuresData.HOLIDAY == "Y", 1,0)

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
ynLabelEn = LabelEncoder()

In [37]:
ynLabelEn.fit_transform( featuresData.HOLIDAY )

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1])

In [38]:
featuresData["LE_HOLI"] = ynLabelEn.fit_transform( featuresData.HOLIDAY )

In [39]:
featuresData

REGIONID PRODUCTGROUP      PRODUCT      ITEM  YEARWEEK  YEAR  WEEK  \
0    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201501  2015     1   
1    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201502  2015     2   
2    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201503  2015     3   
3    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201504  2015     4   
4    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201505  2015     5   
..              ...          ...          ...       ...       ...   ...   ...   
100  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201648  2016    48   
101  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201649  2016    49   
102  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201650  2016    50   
103  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201651  2016    51   
104  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201652  2016    52   

        QTY HOLIDAY  HCLUS PROMOTION  PRO_PERCENT  LE_HOLI  
0    1225.0       Y      1         Y     0.209442        1  
1     968.0       N      4         Y     0.209442        0  
2    1209.0       N      4         Y     0.208155        0  
3    1810.0       Y      2         Y     0.208155        1  
4    1773.0       N      4         Y     0.208155        0  
..      ...     ...    ...       ...          ...      ...  
100  2412.0       Y      0         Y     0.421888        1  
101  1955.0       N      4         Y     0.421888        0  
102  1800.0       N      4         Y     0.352361        0  
103  1173.0       N      4         Y     0.352361        0  
104   332.0       Y      1         Y     0.352361        1  

[105 rows x 13 columns]

In [40]:
ynLabelEn.inverse_transform( featuresData["LE_HOLI"] )

array(['Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N',
       'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N',
       'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y',
       'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N',
       'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N',
       'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'Y'], dtype=object)

In [41]:
featuresData["LE_HOLI_IN"] = ynLabelEn.inverse_transform( featuresData["LE_HOLI"] )

In [42]:
featuresData.loc[ featuresData.LE_HOLI_IN != featuresData.HOLIDAY]

Empty DataFrame
Columns: [REGIONID, PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK, YEAR, WEEK, QTY, HOLIDAY, HCLUS, PROMOTION, PRO_PERCENT, LE_HOLI, LE_HOLI_IN]
Index: []

In [43]:
featuresData = featuresData.drop( columns =["LE_HOLI_IN"] )

In [44]:
featuresData

REGIONID PRODUCTGROUP      PRODUCT      ITEM  YEARWEEK  YEAR  WEEK  \
0    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201501  2015     1   
1    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201502  2015     2   
2    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201503  2015     3   
3    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201504  2015     4   
4    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201505  2015     5   
..              ...          ...          ...       ...       ...   ...   ...   
100  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201648  2016    48   
101  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201649  2016    49   
102  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201650  2016    50   
103  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201651  2016    51   
104  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201652  2016    52   

        QTY HOLIDAY  HCLUS PROMOTION  PRO_PERCENT  LE_HOLI  
0    1225.0       Y      1         Y     0.209442        1  
1     968.0       N      4         Y     0.209442        0  
2    1209.0       N      4         Y     0.208155        0  
3    1810.0       Y      2         Y     0.208155        1  
4    1773.0       N      4         Y     0.208155        0  
..      ...     ...    ...       ...          ...      ...  
100  2412.0       Y      0         Y     0.421888        1  
101  1955.0       N      4         Y     0.421888        0  
102  1800.0       N      4         Y     0.352361        0  
103  1173.0       N      4         Y     0.352361        0  
104   332.0       Y      1         Y     0.352361        1  

[105 rows x 13 columns]

In [45]:
!pip install ultralytics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.2/755.2 kB 8.6 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-many

In [46]:
pd.read_csv("../dataset/kopo_channel_seasonality_new.csv")

REGIONID    PRODUCT  YEARWEEK      QTY
0           A60   PRODUCT4    201402     71.0
1           A60  PRODUCT59    201402  22275.0
2           A60  PRODUCT34    201402   4463.0
3           A60  PRODUCT47    201402      0.0
4           A60  PRODUCT56    201402     23.0
...         ...        ...       ...      ...
124653      A10  PRODUCT60    201630    824.0
124654      A10  PRODUCT56    201630    275.0
124655      A10  PRODUCT61    201630      0.0
124656      A10  PRODUCT12    201630  15021.0
124657      A10   PRODUCT1    201630    568.0

[124658 rows x 4 columns]

In [47]:
selloutData = pd.read_csv("../dataset/kopo_channel_seasonality_new.csv")

In [48]:
selloutData

REGIONID    PRODUCT  YEARWEEK      QTY
0           A60   PRODUCT4    201402     71.0
1           A60  PRODUCT59    201402  22275.0
2           A60  PRODUCT34    201402   4463.0
3           A60  PRODUCT47    201402      0.0
4           A60  PRODUCT56    201402     23.0
...         ...        ...       ...      ...
124653      A10  PRODUCT60    201630    824.0
124654      A10  PRODUCT56    201630    275.0
124655      A10  PRODUCT61    201630      0.0
124656      A10  PRODUCT12    201630  15021.0
124657      A10   PRODUCT1    201630    568.0

[124658 rows x 4 columns]

In [49]:
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK      int64
QTY         float64
dtype: object

In [50]:
regionEn = LabelEncoder()

In [51]:
regionEn.fit_transform( selloutData.REGIONID )

array([58, 58, 58, ..., 10, 10, 10])

In [52]:
selloutData["LE_REGIONID"] = regionEn.fit_transform( selloutData.REGIONID )

In [53]:
selloutData

REGIONID    PRODUCT  YEARWEEK      QTY  LE_REGIONID
0           A60   PRODUCT4    201402     71.0           58
1           A60  PRODUCT59    201402  22275.0           58
2           A60  PRODUCT34    201402   4463.0           58
3           A60  PRODUCT47    201402      0.0           58
4           A60  PRODUCT56    201402     23.0           58
...         ...        ...       ...      ...          ...
124653      A10  PRODUCT60    201630    824.0           10
124654      A10  PRODUCT56    201630    275.0           10
124655      A10  PRODUCT61    201630      0.0           10
124656      A10  PRODUCT12    201630  15021.0           10
124657      A10   PRODUCT1    201630    568.0           10

[124658 rows x 5 columns]

In [54]:
regionEn.classes_

array(['A00', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08',
       'A09', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17',
       'A18', 'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26',
       'A27', 'A28', 'A29', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36',
       'A37', 'A38', 'A39', 'A40', 'A41', 'A42', 'A43', 'A44', 'A45',
       'A46', 'A47', 'A48', 'A50', 'A51', 'A52', 'A53', 'A54', 'A55',
       'A56', 'A57', 'A58', 'A59', 'A60', 'A61', 'A62', 'A63', 'A64',
       'A65', 'A66', 'A67', 'A68', 'A69', 'A70', 'A77'], dtype=object)

In [55]:
regionEn.inverse_transform( selloutData["LE_REGIONID"] )

array(['A60', 'A60', 'A60', ..., 'A10', 'A10', 'A10'], dtype=object)