In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/Colab Notebooks/std2024/Session07 - 유형별로 실습하는 머신러닝

/content/drive/MyDrive/Colab Notebooks/std2024/Session07 - 유형별로 실습하는 머신러닝


In [ ]:
import pandas as pd

In [114]:
featuresData = pd.read_csv("../dataset/feature_regression_example.csv")

#A. 데이터 전처리

### A-1. 타입 통합 / 특성 숫자컬럼 추가

In [ ]:
featuresData

REGIONID PRODUCTGROUP      PRODUCT      ITEM  YEARWEEK  YEAR  WEEK  \
0    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201501  2015     1   
1    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201502  2015     2   
2    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201503  2015     3   
3    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201504  2015     4   
4    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201505  2015     5   
..              ...          ...          ...       ...       ...   ...   ...   
100  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201648  2016    48   
101  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201649  2016    49   
102  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201650  2016    50   
103  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201651  2016    51   
104  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201652  2016    52   

      QTY HOLIDAY  HCLUS PROMOTION  PRO_PERCENT  
0    1225       Y      1         Y     0.209442  
1     968       N      4         Y     0.209442  
2    1209       N      4         Y     0.208155  
3    1810       Y      2         Y     0.208155  
4    1773       N      4         Y     0.208155  
..    ...     ...    ...       ...          ...  
100  2412       Y      0         Y     0.421888  
101  1955       N      4         Y     0.421888  
102  1800       N      4         Y     0.352361  
103  1173       N      4         Y     0.352361  
104   332       Y      1         Y     0.352361  

[105 rows x 12 columns]

In [ ]:
featuresData.HOLIDAY

0      Y
1      N
2      N
3      Y
4      N
      ..
100    Y
101    N
102    N
103    N
104    Y
Name: HOLIDAY, Length: 105, dtype: object

In [ ]:
featuresData.HOLIDAY.drop_duplicates()

0    Y
1    N
Name: HOLIDAY, dtype: object

In [14]:
featuresData["REGIONID"] = featuresData["REGIONID"].astype(str)

In [15]:
featuresData["PRODUCTGROUP"] = featuresData["PRODUCTGROUP"].astype(str)

In [16]:
featuresData["PRODUCT"] = featuresData["PRODUCT"].astype(str)

In [17]:
featuresData["ITEM"] = featuresData["ITEM"].astype(str)

In [18]:
featuresData["YEARWEEK"] = featuresData["YEARWEEK"].astype(int)

In [19]:
featuresData["YEAR"] = featuresData["YEAR"].astype(int)

In [20]:
featuresData["WEEK"] = featuresData["WEEK"].astype(int)

In [21]:
featuresData["QTY"] = featuresData["QTY"].astype(float)

In [22]:
featuresData["HOLIDAY"] = featuresData["HOLIDAY"].astype(str)

In [23]:
featuresData["HCLUS"] = featuresData["HCLUS"].astype(int)

In [25]:
featuresData["PROMOTION"] = featuresData["PROMOTION"].astype(str)

In [26]:
featuresData["PRO_PERCENT"] = featuresData["PRO_PERCENT"].astype(float)

In [27]:
import numpy as np

In [28]:
np.where( featuresData.REGIONID =="Y", 1, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.where( featuresData.HOLIDAY == "Y", 1,0)

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1])

In [34]:
featuresData["LE_HOLI"] = np.where( featuresData.HOLIDAY == "Y", 1,0)

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
ynLabelEn = LabelEncoder()

In [37]:
ynLabelEn.fit_transform( featuresData.HOLIDAY )

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1])

In [38]:
featuresData["LE_HOLI"] = ynLabelEn.fit_transform( featuresData.HOLIDAY )

In [39]:
featuresData

REGIONID PRODUCTGROUP      PRODUCT      ITEM  YEARWEEK  YEAR  WEEK  \
0    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201501  2015     1   
1    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201502  2015     2   
2    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201503  2015     3   
3    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201504  2015     4   
4    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201505  2015     5   
..              ...          ...          ...       ...       ...   ...   ...   
100  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201648  2016    48   
101  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201649  2016    49   
102  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201650  2016    50   
103  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201651  2016    51   
104  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201652  2016    52   

        QTY HOLIDAY  HCLUS PROMOTION  PRO_PERCENT  LE_HOLI  
0    1225.0       Y      1         Y     0.209442        1  
1     968.0       N      4         Y     0.209442        0  
2    1209.0       N      4         Y     0.208155        0  
3    1810.0       Y      2         Y     0.208155        1  
4    1773.0       N      4         Y     0.208155        0  
..      ...     ...    ...       ...          ...      ...  
100  2412.0       Y      0         Y     0.421888        1  
101  1955.0       N      4         Y     0.421888        0  
102  1800.0       N      4         Y     0.352361        0  
103  1173.0       N      4         Y     0.352361        0  
104   332.0       Y      1         Y     0.352361        1  

[105 rows x 13 columns]

In [40]:
ynLabelEn.inverse_transform( featuresData["LE_HOLI"] )

array(['Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N',
       'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N',
       'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y',
       'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N',
       'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N',
       'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'Y'], dtype=object)

In [41]:
featuresData["LE_HOLI_IN"] = ynLabelEn.inverse_transform( featuresData["LE_HOLI"] )

In [42]:
featuresData.loc[ featuresData.LE_HOLI_IN != featuresData.HOLIDAY]

Empty DataFrame
Columns: [REGIONID, PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK, YEAR, WEEK, QTY, HOLIDAY, HCLUS, PROMOTION, PRO_PERCENT, LE_HOLI, LE_HOLI_IN]
Index: []

In [43]:
featuresData = featuresData.drop( columns =["LE_HOLI_IN"] )

In [44]:
featuresData

REGIONID PRODUCTGROUP      PRODUCT      ITEM  YEARWEEK  YEAR  WEEK  \
0    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201501  2015     1   
1    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201502  2015     2   
2    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201503  2015     3   
3    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201504  2015     4   
4    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201505  2015     5   
..              ...          ...          ...       ...       ...   ...   ...   
100  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201648  2016    48   
101  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201649  2016    49   
102  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201650  2016    50   
103  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201651  2016    51   
104  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201652  2016    52   

        QTY HOLIDAY  HCLUS PROMOTION  PRO_PERCENT  LE_HOLI  
0    1225.0       Y      1         Y     0.209442        1  
1     968.0       N      4         Y     0.209442        0  
2    1209.0       N      4         Y     0.208155        0  
3    1810.0       Y      2         Y     0.208155        1  
4    1773.0       N      4         Y     0.208155        0  
..      ...     ...    ...       ...          ...      ...  
100  2412.0       Y      0         Y     0.421888        1  
101  1955.0       N      4         Y     0.421888        0  
102  1800.0       N      4         Y     0.352361        0  
103  1173.0       N      4         Y     0.352361        0  
104   332.0       Y      1         Y     0.352361        1  

[105 rows x 13 columns]

In [45]:
!pip install ultralytics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.2/755.2 kB 8.6 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-many

In [46]:
pd.read_csv("../dataset/kopo_channel_seasonality_new.csv")

REGIONID    PRODUCT  YEARWEEK      QTY
0           A60   PRODUCT4    201402     71.0
1           A60  PRODUCT59    201402  22275.0
2           A60  PRODUCT34    201402   4463.0
3           A60  PRODUCT47    201402      0.0
4           A60  PRODUCT56    201402     23.0
...         ...        ...       ...      ...
124653      A10  PRODUCT60    201630    824.0
124654      A10  PRODUCT56    201630    275.0
124655      A10  PRODUCT61    201630      0.0
124656      A10  PRODUCT12    201630  15021.0
124657      A10   PRODUCT1    201630    568.0

[124658 rows x 4 columns]

In [47]:
selloutData = pd.read_csv("../dataset/kopo_channel_seasonality_new.csv")

In [48]:
selloutData

REGIONID    PRODUCT  YEARWEEK      QTY
0           A60   PRODUCT4    201402     71.0
1           A60  PRODUCT59    201402  22275.0
2           A60  PRODUCT34    201402   4463.0
3           A60  PRODUCT47    201402      0.0
4           A60  PRODUCT56    201402     23.0
...         ...        ...       ...      ...
124653      A10  PRODUCT60    201630    824.0
124654      A10  PRODUCT56    201630    275.0
124655      A10  PRODUCT61    201630      0.0
124656      A10  PRODUCT12    201630  15021.0
124657      A10   PRODUCT1    201630    568.0

[124658 rows x 4 columns]

In [49]:
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK      int64
QTY         float64
dtype: object

In [50]:
regionEn = LabelEncoder()

In [51]:
regionEn.fit_transform( selloutData.REGIONID )

array([58, 58, 58, ..., 10, 10, 10])

In [52]:
selloutData["LE_REGIONID"] = regionEn.fit_transform( selloutData.REGIONID )

In [53]:
selloutData

REGIONID    PRODUCT  YEARWEEK      QTY  LE_REGIONID
0           A60   PRODUCT4    201402     71.0           58
1           A60  PRODUCT59    201402  22275.0           58
2           A60  PRODUCT34    201402   4463.0           58
3           A60  PRODUCT47    201402      0.0           58
4           A60  PRODUCT56    201402     23.0           58
...         ...        ...       ...      ...          ...
124653      A10  PRODUCT60    201630    824.0           10
124654      A10  PRODUCT56    201630    275.0           10
124655      A10  PRODUCT61    201630      0.0           10
124656      A10  PRODUCT12    201630  15021.0           10
124657      A10   PRODUCT1    201630    568.0           10

[124658 rows x 5 columns]

In [54]:
regionEn.classes_

array(['A00', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08',
       'A09', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17',
       'A18', 'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26',
       'A27', 'A28', 'A29', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36',
       'A37', 'A38', 'A39', 'A40', 'A41', 'A42', 'A43', 'A44', 'A45',
       'A46', 'A47', 'A48', 'A50', 'A51', 'A52', 'A53', 'A54', 'A55',
       'A56', 'A57', 'A58', 'A59', 'A60', 'A61', 'A62', 'A63', 'A64',
       'A65', 'A66', 'A67', 'A68', 'A69', 'A70', 'A77'], dtype=object)

In [55]:
regionEn.inverse_transform( selloutData["LE_REGIONID"] )

array(['A60', 'A60', 'A60', ..., 'A10', 'A10', 'A10'], dtype=object)

In [61]:
customerData = pd.read_csv("../dataset/customerdata.csv")

In [59]:
csidLabel = LabelEncoder()

In [62]:
csidLabel.fit_transform( customerData.CUSTID )

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [63]:
customerData["NEW_CUSTID"] = csidLabel.fit_transform( customerData.CUSTID )

In [64]:
customerData

CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE  \
0    A13566  4273.900000    3            6    1.679181  Big-Screen-lover   
1    A14219  3642.441950    2            4    2.682023      Sleeping-dog   
2    A15312  3653.884565    2            5    3.208202      Sleeping-dog   
3    A16605  3713.211107    2            6    0.900000        Early-bird   
4    B10634  3391.074215    2            4    2.453656      Sleeping-dog   
..      ...          ...  ...          ...         ...               ...   
145  Z13253  3678.800000    2            5    2.463670  Big-Screen-lover   
146  Z13534  3662.437527    3            6    0.900000        Early-bird   
147  Z16428  3516.500000    2            5    2.371301  Big-Screen-lover   
148  Z16735  3300.100000    2            5    1.704942  Big-Screen-lover   
149  Z19835  3326.526183    2            6    1.200000        Early-bird   

     NEW_CUSTID  
0             0  
1             1  
2             2  
3             3  
4             4  
..          ...  
145         145  
146         146  
147         147  
148         148  
149         149  

[150 rows x 7 columns]

In [66]:
csMaster = customerData.loc[ :, ["CUSTID", "NEW_CUSTID"] ]
csMaster

CUSTID  NEW_CUSTID
0    A13566           0
1    A14219           1
2    A15312           2
3    A16605           3
4    B10634           4
..      ...         ...
145  Z13253         145
146  Z13534         146
147  Z16428         147
148  Z16735         148
149  Z19835         149

[150 rows x 2 columns]

In [67]:
csMaster = customerData.loc[ :, ["CUSTID", "NEW_CUSTID"] ]
csMaster.to_csv("./master.csv")

In [68]:
targetColumn = ["NEW_CUSTID","AVGPRICE","EMI","PRODUCTAGE","CUSTTYPE"]

In [69]:
customerData.loc[ :, targetColumn ]

NEW_CUSTID     AVGPRICE  EMI  PRODUCTAGE          CUSTTYPE
0             0  4273.900000    3    1.679181  Big-Screen-lover
1             1  3642.441950    2    2.682023      Sleeping-dog
2             2  3653.884565    2    3.208202      Sleeping-dog
3             3  3713.211107    2    0.900000        Early-bird
4             4  3391.074215    2    2.453656      Sleeping-dog
..          ...          ...  ...         ...               ...
145         145  3678.800000    2    2.463670  Big-Screen-lover
146         146  3662.437527    3    0.900000        Early-bird
147         147  3516.500000    2    2.371301  Big-Screen-lover
148         148  3300.100000    2    1.704942  Big-Screen-lover
149         149  3326.526183    2    1.200000        Early-bird

[150 rows x 5 columns]

In [70]:
csMaster.head(1)

CUSTID  NEW_CUSTID
0  A13566           0

In [72]:
from sklearn.preprocessing import LabelEncoder

In [125]:
ynHoLabel = LabelEncoder()
ynPrLabel = LabelEncoder()

In [126]:
ynLabel.fit_transform( featuresData.HOLIDAY )

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1])

In [127]:
featuresData["LE_HOLI"] = ynHoLabel.fit_transform( featuresData.HOLIDAY )
featuresData["LE_PROMO"] = ynPrLabel.fit_transform( featuresData.PROMOTION )

### A-2. 특성선정 및 데이터분리

In [79]:
corrDf = featuresData.corr(numeric_only=True)
corrDf

YEARWEEK      YEAR      WEEK       QTY     HCLUS  PRO_PERCENT  \
YEARWEEK     1.000000  0.956598  0.275593  0.112267 -0.071586     0.404889   
YEAR         0.956598  1.000000 -0.016493  0.028931  0.028593     0.321193   
WEEK         0.275593 -0.016493  1.000000  0.289766 -0.339943     0.329705   
QTY          0.112267  0.028931  0.289766  1.000000 -0.537230     0.700195   
HCLUS       -0.071586  0.028593 -0.339943 -0.537230  1.000000    -0.545619   
PRO_PERCENT  0.404889  0.321193  0.329705  0.700195 -0.545619     1.000000   
LE_HOLI      0.049867 -0.031106  0.273710  0.505932 -0.974601     0.487062   
LE_PROMO     0.205916  0.195931  0.060206  0.612451 -0.374072     0.898554   

              LE_HOLI  LE_PROMO  
YEARWEEK     0.049867  0.205916  
YEAR        -0.031106  0.195931  
WEEK         0.273710  0.060206  
QTY          0.505932  0.612451  
HCLUS       -0.974601 -0.374072  
PRO_PERCENT  0.487062  0.898554  
LE_HOLI      1.000000  0.365148  
LE_PROMO     0.365148  1.000000

In [80]:
stdRatio = 0.5

In [81]:
corrDf.loc[ corrDf.QTY> stdRatio ]

YEARWEEK      YEAR      WEEK       QTY     HCLUS  PRO_PERCENT  \
QTY          0.112267  0.028931  0.289766  1.000000 -0.537230     0.700195   
PRO_PERCENT  0.404889  0.321193  0.329705  0.700195 -0.545619     1.000000   
LE_HOLI      0.049867 -0.031106  0.273710  0.505932 -0.974601     0.487062   
LE_PROMO     0.205916  0.195931  0.060206  0.612451 -0.374072     0.898554   

              LE_HOLI  LE_PROMO  
QTY          0.505932  0.612451  
PRO_PERCENT  0.487062  0.898554  
LE_HOLI      1.000000  0.365148  
LE_PROMO     0.365148  1.000000

In [82]:
corrDf.loc[ abs(corrDf.QTY) > stdRatio ]

YEARWEEK      YEAR      WEEK       QTY     HCLUS  PRO_PERCENT  \
QTY          0.112267  0.028931  0.289766  1.000000 -0.537230     0.700195   
HCLUS       -0.071586  0.028593 -0.339943 -0.537230  1.000000    -0.545619   
PRO_PERCENT  0.404889  0.321193  0.329705  0.700195 -0.545619     1.000000   
LE_HOLI      0.049867 -0.031106  0.273710  0.505932 -0.974601     0.487062   
LE_PROMO     0.205916  0.195931  0.060206  0.612451 -0.374072     0.898554   

              LE_HOLI  LE_PROMO  
QTY          0.505932  0.612451  
HCLUS       -0.974601 -0.374072  
PRO_PERCENT  0.487062  0.898554  
LE_HOLI      1.000000  0.365148  
LE_PROMO     0.365148  1.000000

In [90]:
corrDf.loc[ ( abs(corrDf.QTY) > stdRatio) &
            ( corrDf.QTY !=1) ]

YEARWEEK      YEAR      WEEK       QTY     HCLUS  PRO_PERCENT  \
HCLUS       -0.071586  0.028593 -0.339943 -0.537230  1.000000    -0.545619   
PRO_PERCENT  0.404889  0.321193  0.329705  0.700195 -0.545619     1.000000   
LE_HOLI      0.049867 -0.031106  0.273710  0.505932 -0.974601     0.487062   
LE_PROMO     0.205916  0.195931  0.060206  0.612451 -0.374072     0.898554   

              LE_HOLI  LE_PROMO  
HCLUS       -0.974601 -0.374072  
PRO_PERCENT  0.487062  0.898554  
LE_HOLI      1.000000  0.365148  
LE_PROMO     0.365148  1.000000

In [92]:
corrDf.loc[ ( abs(corrDf.QTY) > stdRatio) &
            ( corrDf.QTY !=1) ].index

Index(['HCLUS', 'PRO_PERCENT', 'LE_HOLI', 'LE_PROMO'], dtype='object')

In [93]:
features = list( corrDf.loc[ ( abs(corrDf.QTY) > stdRatio) &
            ( corrDf.QTY !=1) ].index )

In [110]:
features

['HCLUS', 'PRO_PERCENT', 'LE_HOLI', 'LE_PROMO']

In [111]:
label = [ "QTY" ]

In [123]:
featuresData

REGIONID PRODUCTGROUP      PRODUCT      ITEM  YEARWEEK  YEAR  WEEK  \
0    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201501  2015     1   
1    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201502  2015     2   
2    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201503  2015     3   
3    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201504  2015     4   
4    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201505  2015     5   
..              ...          ...          ...       ...       ...   ...   ...   
100  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201648  2016    48   
101  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201649  2016    49   
102  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201650  2016    50   
103  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201651  2016    51   
104  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201652  2016    52   

      QTY HOLIDAY  HCLUS PROMOTION  PRO_PERCENT  
0    1225       Y      1         Y     0.209442  
1     968       N      4         Y     0.209442  
2    1209       N      4         Y     0.208155  
3    1810       Y      2         Y     0.208155  
4    1773       N      4         Y     0.208155  
..    ...     ...    ...       ...          ...  
100  2412       Y      0         Y     0.421888  
101  1955       N      4         Y     0.421888  
102  1800       N      4         Y     0.352361  
103  1173       N      4         Y     0.352361  
104   332       Y      1         Y     0.352361  

[105 rows x 12 columns]

In [122]:
featuresData.shape

(105, 12)

In [99]:
featuresData.shape[0]

105

In [100]:
splitRatio = 0.8

In [102]:
int ( featuresData.shape[0] * splitRatio )

84

In [103]:
stdIndex = int ( featuresData.shape[0] * splitRatio )

In [104]:
sortKey = ["REGIONID", "ITEM", "YEARWEEK"]

In [115]:
featuresData = featuresData.sort_values(by=sortKey).reset_index(drop=True)

In [116]:
featuresData

REGIONID PRODUCTGROUP      PRODUCT      ITEM  YEARWEEK  YEAR  WEEK  \
0    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201501  2015     1   
1    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201502  2015     2   
2    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201503  2015     3   
3    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201504  2015     4   
4    SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201505  2015     5   
..              ...          ...          ...       ...       ...   ...   ...   
100  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201648  2016    48   
101  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201649  2016    49   
102  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201650  2016    50   
103  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201651  2016    51   
104  SEOUL_BANK_001         PG02  PRODUCT0010  ITEM0115    201652  2016    52   

      QTY HOLIDAY  HCLUS PROMOTION  PRO_PERCENT  
0    1225       Y      1         Y     0.209442  
1     968       N      4         Y     0.209442  
2    1209       N      4         Y     0.208155  
3    1810       Y      2         Y     0.208155  
4    1773       N      4         Y     0.208155  
..    ...     ...    ...       ...          ...  
100  2412       Y      0         Y     0.421888  
101  1955       N      4         Y     0.421888  
102  1800       N      4         Y     0.352361  
103  1173       N      4         Y     0.352361  
104   332       Y      1         Y     0.352361  

[105 rows x 12 columns]

In [117]:
featuresData.loc[ stdIndex, ["YEARWEEK"] ]

YEARWEEK    201632
Name: 84, dtype: object

In [118]:
featuresData.loc[ stdIndex, ["YEARWEEK"] ].values

array([201632], dtype=object)

In [120]:
stdYearweek = featuresData.loc[ stdIndex, ["YEARWEEK"] ].values[0]
stdYearweek

201632

In [128]:
trainingDataFeatures = featuresData.loc[  featuresData.YEARWEEK <= stdYearweek, features ]
trainingDataFeatures

HCLUS  PRO_PERCENT  LE_HOLI  LE_PROMO
0       1     0.209442        1         1
1       4     0.209442        0         1
2       4     0.208155        0         1
3       2     0.208155        1         1
4       4     0.208155        0         1
..    ...          ...      ...       ...
80      1     0.308584        1         1
81      1     0.308584        1         1
82      4     0.280258        0         1
83      4     0.280258        0         1
84      4     0.280258        0         1

[85 rows x 4 columns]

In [129]:
trainingDataFeatures = featuresData.loc[  featuresData.YEARWEEK <= stdYearweek, features ]
trainingDataLabel = featuresData.loc[ featuresData.YEARWEEK <= stdYearweek, label ]
trainingDataLabel

QTY
0   1225
1    968
2   1209
3   1810
4   1773
..   ...
80  1616
81  1318
82  2240
83  1522
84  2100

[85 rows x 1 columns]

In [132]:
trainingDataFeatures = featuresData.loc[  featuresData.YEARWEEK <= stdYearweek, features ]
trainingDataLabel = featuresData.loc[ featuresData.YEARWEEK <= stdYearweek, label ]
testDataFeatures = featuresData.loc[ featuresData.YEARWEEK > stdYearweek, features ]
testDataFeatures

HCLUS  PRO_PERCENT  LE_HOLI  LE_PROMO
85       4     0.000000        0         0
86       1     0.308584        1         1
87       1     0.308584        1         1
88       1     0.308584        1         1
89       4     0.308584        0         1
90       4     0.308584        0         1
91       4     0.280258        0         1
92       4     0.280258        0         1
93       2     0.280258        1         1
94       4     0.280258        0         1
95       4     0.000000        0         0
96       0     0.421888        1         1
97       0     0.421888        1         1
98       0     0.421888        1         1
99       0     0.421888        1         1
100      0     0.421888        1         1
101      4     0.421888        0         1
102      4     0.352361        0         1
103      4     0.352361        0         1
104      1     0.352361        1         1

In [134]:
trainingDataFeatures = featuresData.loc[  featuresData.YEARWEEK <= stdYearweek, features ]
trainingDataLabel = featuresData.loc[ featuresData.YEARWEEK <= stdYearweek, label ]
testDataFeatures = featuresData.loc[ featuresData.YEARWEEK > stdYearweek, features ]
testDataLabel = featuresData.loc[ featuresData.YEARWEEK > stdYearweek, label ]
testDataLabel

QTY
85     43
86   1700
87   1514
88   1501
89   1491
90    806
91   2111
92   2400
93   2010
94   1900
95    141
96   1615
97   1574
98   1800
99   2600
100  2412
101  1955
102  1800
103  1173
104   332

In [135]:
trainingDataFeatures = featuresData.loc[  featuresData.YEARWEEK <= stdYearweek, features ]
trainingDataLabel = featuresData.loc[ featuresData.YEARWEEK <= stdYearweek, label ]
testDataFeatures = featuresData.loc[ featuresData.YEARWEEK > stdYearweek, features ]
testDataLabel = featuresData.loc[ featuresData.YEARWEEK > stdYearweek, label ]

In [136]:
print(trainingDataFeatures.shape)
print(trainingDataLabel.shape)
print(testDataFeatures.shape)
print(testDataLabel.shape)

(85, 4)
(85, 1)
(20, 4)
(20, 1)


#B.모델적용

### B-3.모델 적용

In [137]:
from sklearn import tree
from sklearn import ensemble

In [138]:
# model: DecisionTree
modelDt = tree.DecisionTreeRegressor()
# model: RandomForest
modelRf = ensemble.RandomForestRegressor()

In [139]:
# model: DecisionTree
modelDt = tree.DecisionTreeRegressor(random_state=10)
# model: RandomForest
modelRf = ensemble.RandomForestRegressor(random_state=10)

In [142]:
fittedDtModel = modelDt.fit(X = trainingDataFeatures,
              y = trainingDataLabel )
fittedRfModel = modelRf.fit(X = trainingDataFeatures,
              y = trainingDataLabel )

<ipython-input-142-1e1d05aa7867>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  fittedRfModel = modelRf.fit(X = trainingDataFeatures,


#C.예측

### C-4.예측 및 검증

In [143]:
fittedDtModel.predict(X=testDataFeatures)

array([ 350.71428571, 1434.6       , 1434.6       , 1434.6       ,
       1434.6       , 1434.6       , 1708.75      , 1708.75      ,
       2620.42857143, 1708.75      ,  350.71428571, 2193.8       ,
       2193.8       , 2193.8       , 2193.8       , 2193.8       ,
       1434.6       , 1434.6       , 1434.6       , 1434.6       ])

In [144]:
predictValue = fittedDtModel.predict(X=testDataFeatures)

In [145]:
testDataLabel

QTY
85     43
86   1700
87   1514
88   1501
89   1491
90    806
91   2111
92   2400
93   2010
94   1900
95    141
96   1615
97   1574
98   1800
99   2600
100  2412
101  1955
102  1800
103  1173
104   332

In [146]:
testDataLabel["PREDICT_DT"] = 1
testDataLabel

QTY  PREDICT_DT
85     43           1
86   1700           1
87   1514           1
88   1501           1
89   1491           1
90    806           1
91   2111           1
92   2400           1
93   2010           1
94   1900           1
95    141           1
96   1615           1
97   1574           1
98   1800           1
99   2600           1
100  2412           1
101  1955           1
102  1800           1
103  1173           1
104   332           1

In [147]:
testDataLabel["PREDICT_DT"] = predictValue
testDataLabel

QTY   PREDICT_DT
85     43   350.714286
86   1700  1434.600000
87   1514  1434.600000
88   1501  1434.600000
89   1491  1434.600000
90    806  1434.600000
91   2111  1708.750000
92   2400  1708.750000
93   2010  2620.428571
94   1900  1708.750000
95    141   350.714286
96   1615  2193.800000
97   1574  2193.800000
98   1800  2193.800000
99   2600  2193.800000
100  2412  2193.800000
101  1955  1434.600000
102  1800  1434.600000
103  1173  1434.600000
104   332  1434.600000

In [148]:
features

['HCLUS', 'PRO_PERCENT', 'LE_HOLI', 'LE_PROMO']

In [150]:
inputHClus = 1 #대휴일
inputProPercent = 0.4
inputHoliday = 1
inputPromotion = 1

In [156]:
inputData = pd.DataFrame( [[inputHClus, inputProPercent, inputHoliday, inputPromotion]])

In [157]:
inputData

0    1  2  3
0  1  0.4  1  1

In [163]:
result = fittedDtModel.predict(inputData)
result

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([1434.6])

In [164]:
result = fittedDtModel.predict(inputData)
result[0]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


1434.6

In [165]:
import pickle

In [166]:
with open("./midtcore.dump", "wb") as fw:
  pickle.dump(fittedDtModel, fw)

In [167]:
pwd

'/content/drive/MyDrive/Colab Notebooks/std2024/Session07 - 유형별로 실습하는 머신러닝'